### ISSUE TITLE
Show the message as the result of unsubscribe action

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/openexchange#169]
A click on "Mute the notifications from the application" opens the site but shows the empty screen.
It should show the message:
You were successfully unsubscribed from the notifications of the _Application_Name_ application.

**Comment by gjsjohnmurray** [comment]
This seems to be partly fixed. The first time I click on that link in an app notification email I get a good confirmation message. But if by mistake I unsubscribe again from the same application (e.g. because I received several app notification emails while I was away), I get this the second time:

![image](https://user-images.githubusercontent.com/6726799/120459897-86d8e380-c390-11eb-8b64-bfb6b029c458.png)
