### ISSUE TITLE
Automatically enable the "Publish to ZPM" flag if there is a module.xml file in the repo

### ISSUE THREAD

**Issue by SergeyMi37** [intersystems-community/openexchange#241]

**Comment by Lena-Ev** [comment]
Hi Sergey! 
TEchnically we can do this feature but logically it will not work for us, because some of the members use templates which contain  module.xml file but they do not use it and do not remove it. And this people mostly unconscious about that so very unlikely the won't uncheck the box.
If such files will be automatically posted in ZPM it will not work well.
sorry for that, I hope this check box doesn't take too much time of yours.

**Comment by SergeyMi37** [comment]
I suggested that you refused on a motivated basis. The path will be like this.

**Comment by evshvarov** [comment]
I think it’s a good idea. Let’s think more how we can do this
Вт, 14 дек. 2021 г. в 11:43, Sergey Mikhaylenko ***@***.***>:
