### ISSUE TITLE
Allow more than one company member to be an Admin

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/openexchange#245]
The current limit of one Admin member per company  is not good. For example, if the person who is Admin is not available we have to contact InterSystems.

**Comment by gjsjohnmurray** [comment]
Any chance of getting this addressed soon? At the moment only one member of our company can update apps that are published by the company. This appears to include even adding an extra tag to an app.

**Comment by Lena-Ev** [comment]
due to the initial architecture we could not do the several-admins option. But you can transfer now your admin rights to company's members in Members section
There you can also add members to the company, who can have access to all the information and create compeny's products, but can't update company's profile data:
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/77621970/212752393-4a3fcbd3-f6b8-4c9f-844d-10dfda779d30.png">

I hope that will help
